config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :authors
  root 'books#index'

  resources :book_series
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# Base application record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  def fullname
    "#{first_name} #{last_name}"
  end

  def books
    Book.where(author: self)
  end

  def pages_written
    self.books.map { |book| book.pages }.sum
  end
end

app/models/book.rb
# frozen_string_literal: true

# This encapsulates a book
class Book < ApplicationRecord
  belongs_to :book_series, optional: true
  belongs_to :author, optional: true

  # accepts_nested_attributes_for :book_series
  # accepts_nested_attributes_for :author
  #
  validates :title, presence: true
  validates :pub_year, presence: true
end

app/models/book_series.rb
# frozen_string_literal: true

# This is a book series...
class BookSeries < ApplicationRecord
  has_many :books

  validates :title, presence: true

  def book_count
    Book.where(book_series_id: id).count
  end

  def total_pages
    books.map {|book| book.pages}.sum
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/book_series_controller.rb
# frozen_string_literal: true

class BookSeriesController < ApplicationController
  before_action :set_book_series, only: %i[show edit update destroy]

  # GET /book_series
  # GET /book_series.json
  def index
    @book_series = BookSeries.all
  end

  # GET /book_series/1
  # GET /book_series/1.json
  def show; end

  # GET /book_series/new
  def new
    @book_series = BookSeries.new
  end

  # GET /book_series/1/edit
  def edit; end

  # POST /book_series
  # POST /book_series.json
  def create
    @book_series = BookSeries.new(book_series_params)

    respond_to do |format|
      if @book_series.save
        format.html { redirect_to @book_series, notice: 'Book series was successfully created.' }
        format.json { render :show, status: :created, location: @book_series }
      else
        format.html { render :new }
        format.json { render json: @book_series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_series/1
  # PATCH/PUT /book_series/1.json
  def update
    respond_to do |format|
      if @book_series.update(book_series_params)
        format.html { redirect_to @book_series, notice: 'Book series was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_series }
      else
        format.html { render :edit }
        format.json { render json: @book_series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_series/1
  # DELETE /book_series/1.json
  def destroy
    @book_series.destroy
    respond_to do |format|
      format.html { redirect_to book_series_index_url, notice: 'Book series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book_series
    @book_series = BookSeries.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_series_params
    params.require(:book_series).permit(:title)
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :setBook, only: %i[show edit update destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show;
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit;
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if validateBook && @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update

    respond_to do |format|
      if validateBook && @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Validate that there are no other books with this title for the pub year
  #
  def validateBook
    Book.where(title: @book.title, pub_year: @book.pub_year).each do |other|
      if @book.id != other.id
        @book.errors.add(:title, "already exists in publication year.")
        return false
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def setBook
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:title, :pub_year, :pages, :author_id, :book_series_id )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_series_helper.rb
# frozen_string_literal: true

module BookSeriesHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :author_first_name %>
  </div>


  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :author_last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Books</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @authors.each do |author| %>
    <tr>
      <td><%= author.first_name %></td>
      <td><%= author.last_name %></td>
      <td>
        <% unless author.books.empty? %>
          <ul>
            <% author.books.each do |book| %>
              <li><%= link_to book.title, book_path(book) %> (<%= book.pub_year %>)</li>
            <% end %>
          </ul>
        <% end %>
      </td>
      <td><%= link_to 'Show', author %></td>
      <td><%= link_to 'Edit', edit_author_path(author) %></td>
      <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<p>
  <strong>Total books:</strong>
  <%= @author.books.count %>
</p>

  <strong>Pages written:</strong>
  <%= @author.pages_written %>
</p>

<p>
  <strong>Books:</strong>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Pub year</th>
    <th>Pages</th>
    <th>Book Series</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @author.books.each do |book| %>
    <tr>
      <td><%= link_to book.title, book %></td>
      <td><%= link_to book.author.fullname, author_path(book.author) %></td>
      <td><%= book.pub_year %></td>
      <td><%= book.pages %></td>
      <% if book.book_series %>
        <td><%= link_to book.book_series.title, book_series_path(book.book_series) %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/book_series/_form.html.erb
<%= form_with(model: book_series, local: true) do |form| %>
  <% if book_series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_series.errors.count, "error") %> prohibited this book_series from being saved:</h2>

      <ul>
      <% book_series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_series_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_series/edit.html.erb
<h1>Editing Book Series</h1>

<%= render 'form', book_series: @book_series %>

<%= link_to 'Show', @book_series %> |
<%= link_to 'Back', book_series_index_path %>

app/views/book_series/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Series</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Book count</th>
    <th>Total Pages</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @book_series.each do |book_series| %>
    <tr>
      <td><%= book_series.title %></td>
      <td><%= book_series.book_count %></td>
      <td><%= book_series.books.map { |book| book.pages }.sum %></td>
      <td><%= link_to 'Show', book_series %></td>
      <td><%= link_to 'Edit', edit_book_series_path(book_series) %></td>
      <td><%= link_to 'Destroy', book_series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Series', new_book_series_path %>

app/views/book_series/new.html.erb
<h1>New Book Series</h1>

<%= render 'form', book_series: @book_series %>

<%= link_to 'Back', book_series_index_path %>

app/views/book_series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book_series.title %>
</p>

<p>
  <strong>Total Books:</strong>
  <%= @book_series.book_count %>
</p>
<p>
  <strong>Total Pages:</strong>
  <%= @book_series.total_pages %>
</p>

<p>
  <strong>Books:</strong>
  <% if @book_series.books.count == 0 %>
  <div class="alert alert-warning"><%= @book_series.title %> doesn't have any books to display.</div>
<% else %>
  <table class="table" id="books">
    <thead>
    <tr>
      <th>Book Title
        <span data-toggle='tooltip' title='These books are members of the series'><i class='fa fa-question-circle'></i></span>
      </th>
      <th>Author</th>
      <th>Publish Year</th>
      <th>Pages</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @book_series.books.each do |book| %>
      <tr>
        <td>
          <p><%= link_to book.title, book_path(book) %></p>
        </td>
        <td>
          <p><%= link_to book.author.fullname, author_path(book.author) %></p>
        </td>
        <td>
          <p><%= book.pub_year %></p>
        </td>
        <td>
          <p><%= book.pages %></p>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
</p>

<%= link_to 'Edit', edit_book_series_path(@book_series) %> |
<%= link_to 'All Book Series', book_series_index_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.select :author_id, options_for_select(Author.all.map {|author| [author.fullname, author.id]}, book&.author&.id ) %>
  </div>

  <div class="field">
    <%= form.label :book_series %>
      <%= form.select :book_series_id, options_for_select(BookSeries.all.map {|series| [series.title, series.id]}, book&.book_series&.id), include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :pub_year %>
    <%= form.text_field :pub_year, id: :book_pub_year %>
  </div>
  <div class="field">
    <%= form.label :pages %>
    <%= form.text_field :pages, id: :pages %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Pub year</th>
    <th>Pages</th>
    <th>Book Series</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to book.title, book %></td>
      <td>
        <% if book.author %>
          <%= link_to book.author.fullname, author_path(book.author) %>
        <% end %>
      </td>
      <td><%= book.pub_year %></td>
      <td><%= book.pages %></td>
      <% if book.book_series %>
        <td><%= link_to book.book_series.title, book_series_path(book.book_series) %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author&.fullname %>
</p>

<p>
  <strong>Pub year:</strong>
  <%= @book.pub_year %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @book.pages %>
</p>

<% if @book.book_series %>
  <p>
    <strong>Series:</strong>
    <%= link_to @book&.book_series&.title, book_series_path(@book.book_series) %>
  </p>

<% end %>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'All Books', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>